App:
  Name: "cashwhale"

# Logger settings
Log:
  Level: debug
  Color: true
  JSON: false
  EnableFile: false

BCH:
  Nodes:
    - Address: ""
      User: ""
      Password: ""
      SSL: false
      Fulcrum: ""

BCHD:
  # BCHD servers: bchd.imaginary.cash:8335 or bchd.greyh.at:8335, bchd.fountainhead.cash:443, bchd.cashtippr.com:8335
  # https://github.com/simpleledgerinc/grpc-bchrpc-node#bchd-servers
  Address: "bchd.imaginary.cash:8335"
  AuthenticationToken: ""
  RootCertFile: ""
  CaDomain: ""
  AllowSelfSigned: true

Message:
  # message without TX fees
  #Text: "{{.Amount}} #{{.Currency}} #{{.Symbol}} ({{.FiatAmount}} {{.FiatSymbol}}) transferred\n\nTX: {{.TxLink}}"
  # message including TX fees
  Text: "{{.Amount}} #{{.Currency}} #{{.Symbol}} ({{.FiatAmount}} {{.FiatSymbol}}) transferred with {{.FiatFee}} {{.FiatSymbol}} TX fee\n\nTX: {{.TxLink}}"

  BlockExplorer: "https://explorer.bitcoin.com/bch/tx/%s"
  FiatCurrency: "USD"
  WahleThresholdBCH: 20000.0

# monitoring JSON of this process available at: http://your-ip:8686/monitoring
Monitoring:
  Enable: true
  Address: ":8686"

  TweetThresholdH: 24 # notify error if no tweets sent

# Twitter config
Twitter:
  Enable: true
  ConsumerKey: ""
  ConsumerSecret: ""
  AccessToken: ""
  AccessSecret: ""

Price:
  API:
    # available currencies: https://index.bitcoin.com/#10
    USD: "https://index-api.bitcoin.com/api/v0/cash/price/usd"

Notify:
  - Method: "" # pushover|telegram|email
    AppToken: ""
    Receiver: ""